---
title: "Creating a GitHub Account"
author: "Jubilee Bayya"
date: "2022-12-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 1
During week 1, I reviewed my Rstudio workspace and learned how to create an R Markdown notebook. The discussion for the week focused on model performance and overfitting.

## Week 2
During week 2, I learned new R Tools to explore data using summary statistics and visualization, and how to clean up data that has missing values (NAs).

## Week 3
During week 3, I learned how to perform linear regression in R and how to interpret those results. I also perfomed basic hypothesis testing on the linear regression model.

## Week 4
During week 4, I learned how to build a logistic regression model and how to evaluate the performance of a classifer using a confusion matrix. When evaluating a model's performance, we need to balance the accuracy of our precision and recall measurements.

## Week 5
During week 5, I compared simple linear regression models with Generalized Linear Models (GLM). There are different types of generalized linear models to use dependent on the dataset's characteristics.

## Week 6
During week 6, I learned more about decision tree models and how to create  a random forest model. In a random forest model, we can determine which predictors are most important.

## Week 7
During week 7, I learned about K-Means clustering and how to determine the optimal number of clusters and the the elements in each cluster.

## Week 8
During week 8, I learned how to create presentation slides in R and a GitHub account.